### ISSUE TITLE
Come up with website design

### ISSUE THREAD

**Issue by J-Obog** [WomB0ComB0/InterviewBot#1]
Come up with a design for how the website should look and feel. Initial pages are: Landing, Tutorial, Interview

- [x] Crude sketch (very basic design without any colors or logos, core components for each page)
- [x] Fleshed out design (design with colors and some styling)
- [x] Final draft (complete design with colors, logos, graphics, fonts)

**Comment by WomB0ComB0** [comment]
Almost done with the logo, Cross sections anti for the characters/letters (image) then probably a svg slash/back-slash followed by regular cursive-like text

**Comment by WomB0ComB0** [comment]
Already chose a font, need to make root elements

**Comment by WomB0ComB0** [comment]
Made the logo, chose the colors. Done with sketches and formatting.

**Comment by WomB0ComB0** [comment]
Not complete with the html, css, js formatting
